export class UsersTable {
  public static users: any = [
    {
      id: 1,
      username: 'admin',
      password: 'demo',
      email: 'jose.sc@demo.com',
      authToken: 'auth-token-8f3ae836da744329a6f93bf20594b5cc',
      refreshToken: 'auth-token-f8c137a2c98743f48b643e71161d90aa',
      roles: [1], // Administrator
      pic: './assets/media/avatars/300-1.jpg',
      fullname: 'José L. Sánchez C.',
      firstname: 'José Luis',
      lastname: 'Sánchez Cervantes',
      occupation: 'Administrador de Sistemas',
      companyName: 'CEPAT',
      phone: '2721578495',
      language: 'es',
      timeZone: 'Ciudad de México, CDMX',
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      address: {
        addressLine: 'Oriente 9 Emiliano Zapata',
        city: 'Orizaba',
        state: 'Veracruz',
        postCode: '94320',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/jose_luis_sc',
        facebook: 'https://facebook.com/jose_luis_sc',
        twitter: 'https://twitter.com/jose_luis_sc',
        instagram: 'https://instagram.com/jose_luis_sc',
      },
      website: 'jose-luis-sc.com',
    },
    {
      id: 2,
      username: 'user',
      password: 'demo',
      email: 'user@demo.com',
      authToken: 'auth-token-6829bba69dd3421d8762-991e9e806dbf',
      refreshToken: 'auth-token-f8e4c61a318e4d618b6c199ef96b9e55',
      roles: [2], // Coordinator
      pic: './assets/media/avatars/300-6.jpg',
      fullname: 'Megan F',
      firstname: 'Megan',
      lastname: 'Fox',
      occupation: 'Deputy Head of Keenthemes in New York office',
      companyName: 'Keenthemes',
      phone: '456669067891',
      language: 'es',
      timeZone: 'International Date Line West',
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      address: {
        addressLine: '3487  Ingram Road',
        city: 'Greensboro',
        state: 'North Carolina',
        postCode: '27409',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/user',
        facebook: 'https://facebook.com/user',
        twitter: 'https://twitter.com/user',
        instagram: 'https://instagram.com/user',
      },
    },
    {
      id: 3,
      username: 'guest',
      password: 'demo',
      email: 'luis.rh@demo.com',
      authToken: 'auth-token-d2dff7b82f784de584b60964abbe45b9',
      refreshToken: 'auth-token-c999ccfe74aa40d0aa1a64c5e620c1a5',
      roles: [3], // Guest
      pic: './assets/media/avatars/300-1.jpg',
      fullname: 'Luis Angel',
      firstname: 'Luis Angel',
      lastname: 'Reyes Hernandez',
      occupation: 'Maestro en Sistemas Computacionales',
      companyName: 'TecNM / Instituto Tecnológico de Orizaba',
      phone: '2709067892',
      language: 'es',
      timeZone: 'International Date Line West',
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      address: {
        addressLine: '1467  Griffin Street',
        city: 'Phoenix',
        state: 'Arizona',
        postCode: '85012',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/guest',
        facebook: 'https://facebook.com/guest',
        twitter: 'https://twitter.com/guest',
        instagram: 'https://instagram.com/guest',
      },
    },
    {
      id: 4,
      username: 'coordinador',
      password: 'demo',
      email: 'teresita.lv@demo.com',
      authToken: 'auth-token-c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2',
      refreshToken: 'auth-token-e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6',
      roles: [2], // Coordinator
      pic: './assets/media/avatars/300-20.jpg',
      fullname: 'Teresita López Venegas',
      firstname: 'Teresita',
      lastname: 'López Venegas',
      occupation: 'Coordinador TI',
      companyName: 'ITO',
      phone: '2721105360',
      language: 'es',
      timeZone: 'Ciudad de México, CDMX',
      communication: {
        email: true,
        sms: true,
        phone: false,
      },
      address: {
        addressLine: 'Oriente 9 Emiliano Zapata',
        city: 'Orizaba',
        state: 'Veracruz',
        postCode: '94320',
      },
      socialNetworks: {
        linkedIn: 'https://linkedin.com/teresitav',
        facebook: 'https://facebook.com/teresitav',
        twitter: 'https://twitter.com/teresitav',
        instagram: 'https://instagram.com/teresitav',
      },
      website: 'teresitavenegas.com',
    },
  ];

  public static tokens: any = [
    {
      id: 1,
      authToken: 'auth-token-' + Math.random(),
      refreshToken: 'auth-token-' + Math.random(),
    },
  ];
}
